// templates/react-express-emailonly/src/components/header.js
import { useUser } from '../lib/hooks';
import { Link } from 'react-router-dom';

const Header = () => {
  const user = useUser();

  return (
    <header>
      <nav>
        <ul>
          <li>
            <Link to='/'>
              <span>Home</span>
            </Link>
          </li>
          {user ? (
            <>
              <li>
                <Link to='/profile'>
                  <span>Profile</span>
                </Link>
              </li>
              <li>
                <a href={`${process.env.REACT_APP_SERVER_URL}/api/logout`}>Logout</a>
              </li>
            </>
          ) : (
            <li>
              <Link to='/login'>
                <span>Login</span>
              </Link>
            </li>
          )}
        </ul>
      </nav>
      <style>{`
        nav {
          max-width: 42rem;
          margin: 0 auto;
          padding: 0.2rem 1.25rem;
        }
        ul {
          display: flex;
          list-style: none;
          margin-left: 0;
          padding-left: 0;
        }
        li {
          margin-right: 1rem;
        }
        li:first-child {
          margin-left: auto;
        }
        a {
          color: #fff;
          text-decoration: none;
        }
        header {
          color: #fff;
          background-color: #333;
        }
      `}</style>
    </header>
  );
};

export default Header;

// scaffolds/nuxt/template/components/Header.vue
<template>
  <header>
    <nav>
      <ul v-if="$store.state.authenticated">
        <li><NuxtLink to="/">Home</NuxtLink></li>
        <li><NuxtLink to="/profile">Profile</NuxtLink></li>
        <li><a class="logout" @click="userLogout">Logout</a></li>
      </ul>
      <ul v-else>
        <li>
          <a class="logout">Magic Nuxt Demo</a>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script>
export default {
  methods: {
    async userLogout() {
      this.$store.dispatch('logout')
    },
  },
}
</script>

<style>
nav {
  max-width: 45rem;
  margin: 0 auto 50px;
  padding: 1.25rem 1.25rem;
  border-bottom: 1px solid #f0f0f0;
}
ul {
  display: flex;
  list-style: none;
}
li {
  margin-right: 1.5rem;
  line-height: 38px;
}
li:first-child {
  margin-left: auto;
}
a {
  text-decoration: none;
  color: rgba(103, 81, 255, 1);
}
a:hover {
  color: rgba(103, 81, 255, 0.5);
}
.logout {
  color: rgba(191, 144, 69, 1);
  cursor: pointer;
}
.logout:hover {
  color: rgba(191, 144, 69, 0.8);
}
</style>
